### ISSUE TITLE
AttributeError: 'VNCEnv' object has no attribute 'remote_manager'

### ISSUE THREAD

**Issue by Professor-OG** [llSourcell/OpenAI_Game_Bot_Live_stream#7]
What I tried:
adding this after line 35:
   
```
env = gym.make('flashgames.CoasterRacer-v0')
	env.configure(remotes=1)
	observation_n = env.reset()
```

I also tried adding this by itself after line 35:

`    	env.configure(remotes=1)
`
Now im stuck

Here are the contents of terminal:

```
Traceback (most recent call last):
  File "oscarsAIBot.py", line 96, in <module>
    main()
  File "oscarsAIBot.py", line 42, in main
    observation_n = env.reset()
  File "/Users/xcuremac/miniconda3/lib/python3.6/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/Users/xcuremac/universe/universe/wrappers/timer.py", line 18, in _reset
    return self.env.reset()
  File "/Users/xcuremac/miniconda3/lib/python3.6/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/Users/xcuremac/universe/universe/wrappers/render.py", line 28, in _reset
    observation_n = self.env.reset()
  File "/Users/xcuremac/miniconda3/lib/python3.6/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/Users/xcuremac/universe/universe/wrappers/throttle.py", line 42, in _reset
    observation = self.env.reset()
  File "/Users/xcuremac/miniconda3/lib/python3.6/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/Users/xcuremac/universe/universe/envs/vnc_env.py", line 336, in _reset
    self._handle_connect()
  File "/Users/xcuremac/universe/universe/envs/vnc_env.py", line 510, in _handle_connect
    for remote in self.remote_manager.pop(n=n):
AttributeError: 'VNCEnv' object has no attribute 'remote_manager'
```

**Comment by AloshkaD** [comment]
Add the following line

env.configure(remotes=1)
